### ISSUE TITLE
PC: tuple uplifting to methods

### ISSUE THREAD

**Issue by fommil** [fommil/imaginary-friend#18]
say we have this

``` scala
def thing(t: (String, String)): Unit = ???
```

then although the following compiles, it is red squigglied in the PC

``` scala
thing("a", "b")
```

**Comment by dragos** [comment]
I've seen this too. Feels like a regression, but I can't be sure about it.

**Comment by dragos** [comment]
Here's the problem: sbt-esime is trying to be too smart ;-) 

https://github.com/ensime/ensime-sbt/blob/2.0/src/main/scala/EnsimePlugin.scala#L171

**Comment by fommil** [comment]
lol, oh you're kidding!
