### ISSUE TITLE
Example: rewrite as presentation compiler plugin

### ISSUE THREAD

**Issue by fommil** [fommil/imaginary-friend#5]
to demonstrate how a stripped-down presentation compiler plugin can be an alternative to hacking a macro.

**Comment by fommil** [comment]
https://github.com/scala/async/blob/master/src/test/scala/scala/async/run/late/LateExpansion.scala#L420

**Comment by fommil** [comment]
```scala
/**
 * `class`s annotated with `@imaginary` will have the following auto-generated:
 *
 * 1. parameters for `foo` and `bar`, unless provided.
 * 2. `apply` method created on the companion
 * 3. a method on the companion for each `param: T`, named as the parameter, returning `T`.
 */
class imaginary(foo: String, bar: Long) extends StaticAnnotation
```

**Comment by fommil** [comment]
@mlangc @sschaef @dragos possibly the first "result" of this experiment is this helper https://github.com/fommil/imaginary-friend/blob/cc355f6f52b4e3552da0ae9a762bbd5e9f5d76d4/plugin/src/main/scala/fommil/fake.scala#L9-L53

have you come across anything like this?

**Comment by sschaef** [comment]
There are bugs in the PC, which make the scala-ide editor nearly useless for my projects that depend on macros or the macro-paradise compiler plugin. Any fixes in that direction would be welcome. Can't do anything by myself here because fixing the compiler is just too time consuming.

**Comment by fommil** [comment]
Jason pointed me at treeCopy, which most people don't use when they write their macros. It's possible macro paradise has bugs too.
