### ISSUE TITLE
Rename project to Mållgan (google it)

### ISSUE THREAD

**Issue by hedefalk** [fommil/imaginary-friend#9]
…because esoteric Scandinavian names with non ascii letters for extra barrier to adaptation are cool?

**Comment by fommil** [comment]
LOL

**Comment by hedefalk** [comment]
Ooooh, not "wontfix" just yet…

**Comment by hedefalk** [comment]
Darn.

**Comment by fommil** [comment]
ha! Yeah sorry it got renamed to pcplod :stuck_out_tongue: you might need to be British to get the reference...

**Comment by hedefalk** [comment]
Oh, but I read a lot of the Famous Five as a kid though, so not too far
away…

(just had to google it, I hate myself)

**Comment by hedefalk** [comment]
Yeah, if it's not in Faulty Towers I'm lost anyways :(
